apiVersion: v1
kind: Namespace
metadata:
  name: sdfsdfgdfgsdfg-dev
  labels:
    environment-id: env_541f4048-267d-4ed1-86ae-37f6208a9c3e
    project-id: project_39577e69-e7c0-49f6-ba7b-d72d9ad365b2
    project-name: sdfsdfgdfgsdfg
    environment-name: dev
    organization-id: org_9aad87d0-abbc-48f9-9038-002316f0475a
